clear all; clc; 

d = uigetdir;

% temp
% d = '/home/carmine/Code/images_for_qualtrics/test_face/good_configurations_set'

orig_dir = cd;

cd(d)
folder_contents = dir('*.png');
folders_names = regexp(d,filesep,'split');

cd(orig_dir)
fid = fopen('survey_text.txt', 'wt');

fprintf(fid, '[[AdvancedFormat]]\n\n[[Block:1]]\n');
fclose(fid);

cd(orig_dir)
fid = fopen('survey_text.txt', 'a');

for i = 1:length(folder_contents)
    tmp_str = sprintf(...
        ['\n\n[[Question:MC:SingleAnswer:Horizontal]]\n' ...
        '[[ID:Q%i]]\n' ...
       'How much does this image look like a face?\n' ...
       '<img src="https://raw.githubusercontent.com/gnegno/images_for_qualtrics/master/test_face/%s/%s">\n' ...
        '\n[[AdvancedChoices]]\n'...
        '[[Choice:0]]\n'...
        'Doesn''t look like a face at all\n' ...
        '0\n' ...
        '[[Choice:1]]\n'...
        '1\n' ...
        '[[Choice:2]]\n'...
        '2\n'...
        '[[Choice:3]]\n'...
        '3\n'...
        '[[Choice:4]]\n'...
        '4\n'...
        '[[Choice:5]]\n'...
        '5\n'...
        '[[Choice:6]]\n'...
        '6\n'...
        '[[Choice:7]]\n'...
        '7\n' ...
        '[[Choice:8]]\n'...
        '8\n' ...
        '[[Choice:9]]\n'...
        'Clearly a face\n'...
        '9\n' ...
        ], i, folders_names{end}, folder_contents(i).name); 
    
    fprintf(fid, tmp_str);
    
end   

fclose(fid);


 
