clear all; clc; 

d = uigetdir;
folder_contents = dir(d);

txt = '[[AdvancedFormat]]\n';

for i = 1:length({folder_contents.name})
    tmp_str = sprintf(      ...
        ['\n\n[[Block:%i]]\n'    ...
        '[[Question:MC:SingleAnswer:Horizontal]]\n' ...
        'Do you see a face in this image? How difficult it is to see it?\n' ...
        '<img src="https://raw.githubusercontent.com/gnegno/images_for_qualtrics/master/test_face/%s/face_%03d.png">\n' ...
        '[[AdvancedChoices]]\n' ...
        '[[Choice:1]]\n'...
        'Doesn''t look like a face at all\n' ...
        '1\n' ...
        '[[Choice:2]]\n'...
        '2\n'...
        '[[Choice:3]]\n'...
        '3\n'...
        '[[Choice:4]]\n'...
        '4\n'...
        '[[Choice:5]]\n'...
        '5\n'...
        '[[Choice:6]]\n'...
        '6\n'...
        '[[Choice:7]]\n'...
        'Clearly a face\n'...
        '7\n' ...
        ], i, d(end-13:end), i); 
    
    txt = strcat(txt,tmp_str);
    
end   

fid = fopen( 'survey_text.txt', 'wt');
fprintf(fid, txt);
fclose(fid);


 
